### ISSUE TITLE
TiDB cluster deployment

### ISSUE THREAD

**Issue by liufuyang** [YKG/hptc-shichendahai#13]
机器也有了, 不错不错

```
124.196.2.153 -> 10.28.11.181
124.196.2.154 -> 10.28.11.182
124.196.2.155 -> 10.28.11.183
124.196.2.156 -> 10.28.11.184
124.196.2.157 -> 10.28.11.185
124.196.2.158 -> 10.28.11.186
```

topology.yaml:
```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"
pd_servers:
  - host: 10.28.11.181
  - host: 10.28.11.182
  - host: 10.28.11.183
tidb_servers:
  - host: 10.28.11.182
tikv_servers:
  - host: 10.28.11.184
  - host: 10.28.11.185
  - host: 10.28.11.186
monitoring_servers:
  - host: 10.28.11.183
grafana_servers:
  - host: 10.28.11.183
alertmanager_servers:
  - host: 10.28.11.183
```
