### ISSUE TITLE
TiDB opentracing数据对比

### ISSUE THREAD

**Issue by YKG** [YKG/hptc-shichendahai#15]
因为发现threads数量翻倍时，avg latency几乎也同时翻倍，这里我贴一下在playground环境下的一些opentracing结果。

**Comment by YKG** [comment]
配置：

Azure SG节点 L8s_v2

8c64g
nvme 1.8T

```console
ubuntu@ssd:/ssd$ fio -direct=1 -iodepth=128 -rw=randrw -ioengine=libaio -bs=4k -size=1G -numjobs=1 -runtime=1000 -group_reporting -filename=iotest -name=randrw_test
randrw_test: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=128
fio-3.1
Starting 1 process
Jobs: 1 (f=1): [m(1)][-.-%][r=155MiB/s,w=156MiB/s][r=39.7k,w=39.8k IOPS][eta 00m:00s]
randrw_test: (groupid=0, jobs=1): err= 0: pid=7620: Fri Oct 23 10:24:09 2020
   read: IOPS=40.2k, BW=157MiB/s (165MB/s)(512MiB/3260msec)
    slat (usec): min=2, max=745, avg= 7.70, stdev=20.88
    clat (usec): min=785, max=4888, avg=1669.27, stdev=406.01
     lat (usec): min=787, max=4890, avg=1677.47, stdev=406.43
    clat percentiles (usec):
     |  1.00th=[ 1139],  5.00th=[ 1270], 10.00th=[ 1336], 20.00th=[ 1401],
     | 30.00th=[ 1467], 40.00th=[ 1516], 50.00th=[ 1582], 60.00th=[ 1647],
     | 70.00th=[ 1713], 80.00th=[ 1827], 90.00th=[ 2040], 95.00th=[ 2343],
     | 99.00th=[ 3523], 99.50th=[ 3752], 99.90th=[ 4113], 99.95th=[ 4228],
     | 99.99th=[ 4490]
   bw (  KiB/s): min=156488, max=170120, per=100.00%, avg=160795.00, stdev=4848.69, samples=6
   iops        : min=39122, max=42530, avg=40199.00, stdev=1212.25, samples=6
  write: IOPS=40.2k, BW=157MiB/s (165MB/s)(512MiB/3260msec)
    slat (usec): min=2, max=694, avg= 8.88, stdev=22.08
    clat (usec): min=686, max=2862, avg=1490.97, stdev=224.20
     lat (usec): min=699, max=2865, avg=1500.40, stdev=225.47
    clat percentiles (usec):
     |  1.00th=[ 1057],  5.00th=[ 1172], 10.00th=[ 1237], 20.00th=[ 1303],
     | 30.00th=[ 1352], 40.00th=[ 1418], 50.00th=[ 1467], 60.00th=[ 1516],
     | 70.00th=[ 1582], 80.00th=[ 1663], 90.00th=[ 1795], 95.00th=[ 1909],
     | 99.00th=[ 2147], 99.50th=[ 2212], 99.90th=[ 2376], 99.95th=[ 2442],
     | 99.99th=[ 2802]
   bw (  KiB/s): min=156232, max=170232, per=99.85%, avg=160616.67, stdev=4910.12, samples=6
   iops        : min=39058, max=42558, avg=40154.00, stdev=1227.61, samples=6
  lat (usec)   : 750=0.01%, 1000=0.25%
  lat (msec)   : 2=92.66%, 4=6.99%, 10=0.10%
  cpu          : usr=34.27%, sys=65.73%, ctx=16, majf=0, minf=12
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=131040,131104,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128

Run status group 0 (all jobs):
   READ: bw=157MiB/s (165MB/s), 157MiB/s-157MiB/s (165MB/s-165MB/s), io=512MiB (537MB), run=3260-3260msec
  WRITE: bw=157MiB/s (165MB/s), 157MiB/s-157MiB/s (165MB/s-165MB/s), io=512MiB (537MB), run=3260-3260msec

Disk stats (read/write):
  nvme0n1: ios=126541/126566, merge=0/0, ticks=28811/6713, in_queue=0, util=97.07%
ubuntu@ssd:/ssd$
```

**Comment by YKG** [comment]
```
tiup playground nightly --db 1 --db.config tidb.toml --kv 1 --pd 1 --tiflash 0
```

使用 nightly 部署，因为其他版本没有我提交的opentracing PR，没法看到详细的步骤耗时

```toml
# tidb.toml
[opentracing]
# Enable opentracing.
enable = true

# Whether to enable the rpc metrics.
rpc-metrics = true

[opentracing.sampler]
# Type specifies the type of the sampler: const, probabilistic, rateLimiting, or remote
type = "const"

# Param is a value passed to the sampler.
# Valid values for Param field are:
# - for "const" sampler, 0 or 1 for always false/true respectively
# - for "probabilistic" sampler, a probability between 0 and 1
# - for "rateLimiting" sampler, the number of spans per second
# - for "remote" sampler, param is the same as for "probabilistic"
# and indicates the initial sampling rate before the actual one
# is received from the mothership
param = 1.0

# SamplingServerURL is the address of jaeger-agent's HTTP sampling server
sampling-server-url = ""

# MaxOperations is the maximum number of operations that the sampler
# will keep track of. If an operation is not tracked, a default probabilistic
# sampler will be used rather than the per operation specific sampler.
max-operations = 0

# SamplingRefreshInterval controls how often the remotely controlled sampler will poll
# jaeger-agent for the appropriate sampling strategy.
sampling-refresh-interval = 0

[opentracing.reporter]
# QueueSize controls how many spans the reporter can keep in memory before it starts dropping
# new spans. The queue is continuously drained by a background go-routine, as fast as spans
# can be sent out of process.
queue-size = 500000

# BufferFlushInterval controls how often the buffer is force-flushed, even if it's not full.
# It is generally not useful, as it only matters for very low traffic services.
buffer-flush-interval = 0

# LogSpans, when true, enables LoggingReporter that runs in parallel with the main reporter
# and logs all submitted spans. Main Configuration.Logger must be initialized in the code
# for this option to have any effect.
log-spans = false

#  LocalAgentHostPort instructs reporter to send spans to jaeger-agent at this address
local-agent-host-port = ""
```

Jaeger all-in-one: https://github.com/jaegertracing/jaeger/releases/download/v1.20.0/jaeger-1.20.0-linux-amd64.tar.gz

```
./jaeger-all-in-one
```

确认两个端口：
```
ss -lun |grep 6831  # UDP数据接收的地方
ss -ltn |grep 16686 # http访问控制台
```
